"""
SAMSegment — Mask generation block using Segment Anything (via ultralytics).

Runs ultralytics SAM model on each cropped region to produce segmentation
masks.  Optionally accepts point prompts generated by an upstream
glue block.

Input keys:
    crops : list[np.ndarray]  — cropped image regions

Optional input keys:
    point_prompts : list[np.ndarray | None]  — SAM point prompts per crop

Output keys (added):
    masks : list[np.ndarray]  — best mask per crop
"""

from __future__ import annotations

import numpy as np

from blocks.base import Block


class SAMSegment(Block):
    """Generate segmentation masks for each crop using ultralytics SAM."""

    def __init__(self, model) -> None:
        """
        Args:
            model: A loaded ultralytics SAM model instance,
                   e.g. ``SAM("sam_b.pt")``.
        """
        self.model = model

    def __call__(self, data: dict) -> dict:
        # Get crops - if not available, create from boxes
        crops = data.get("crops")
        if crops is None or len(crops) == 0:
            image = data["image"]
            boxes = data.get("boxes", [])
            crops = []
            for box in boxes:
                x1, y1, x2, y2 = map(int, box)
                crops.append(image[y1:y2, x1:x2])
        
        point_prompts = data.get("point_prompts")
        masks: list[np.ndarray] = []

        for i, crop in enumerate(crops):
            # Build optional prompt kwargs
            kwargs: dict = {}
            if point_prompts is not None and point_prompts[i] is not None:
                kwargs["points"] = point_prompts[i].tolist()
                kwargs["labels"] = [1] * len(point_prompts[i])

            results = self.model(crop, **kwargs)

            # Extract mask from results
            if results and results[0].masks is not None:
                mask_data = results[0].masks.data.cpu().numpy()
                # Take the best (first) mask
                masks.append(mask_data[0])
            else:
                # No mask produced — return empty mask matching crop size
                h, w = crop.shape[:2]
                masks.append(np.zeros((h, w), dtype=np.uint8))

        return {
            **data,
            "masks": masks,
        }
